# name: Upload Website

# on:
#   push:
#     branches:
#     - main

# env:
#   BUCKET_NAME : "secrets.AWS_S3_BUCKET"
#   AWS_REGION: "us-east-1"

# # Permission can be added at job level or workflow level    
# permissions:
#       id-token: write   # This is required for requesting the JWT
#       contents: read    # This is required for actions/checkout

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout 
#       uses: actions/checkout@v4
    
#     - name: Configure AWS Credentials
#       uses: aws-actions/configure-aws-credentials@v3
#       with:
#         role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/GithubActions_S3_Sync_TempCred
#         role-session-name: samplerolesession
#         aws-region: ${{ env.AWS_REGION }}
    
#      - name:  Copy index.html to s3
#         run: |
#           aws s3 cp ./Front-end/index.html s3://${{ env.BUCKET_NAME }}/


name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'Front-end'      # optional: defaults to entire repository